# Generated by Django 6.0.2 on 2026-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHabit', models.CharField(max_length=255)),
                ('idUser', models.IntegerField()),
                ('meta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyHabitManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
