# Generated by Django 6.0.2 on 2026-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nameUser', models.CharField(max_length=255, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
