# Generated by Django 6.0.2 on 2026-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
